name: Publish Docker images

on:
  push:
    branches:
      - 'master'

jobs:
  build_2-17-0-pg16-1-18-0:
    name: 2.17.0-pg16-1.18.0
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dontomika/timescaledb-with-toolkit
          tags: 2.17.0-pg16-1.18.0
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./2.17.0-pg16-1.18.0
          file: ./2.17.0-pg16-1.18.0/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_2-24-0-pg16-1-22-0:
    name: 2.24.0-pg16-1.22.0
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dontomika/timescaledb-with-toolkit
          tags: 2.24.0-pg16-1.22.0
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./2.24.0-pg16-1.22.0
          file: ./2.24.0-pg16-1.22.0/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_2-24-0-pg17-1-22-0:
    name: 2.24.0-pg17-1.22.0
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dontomika/timescaledb-with-toolkit
          tags: 2.24.0-pg17-1.22.0
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./2.24.0-pg17-1.22.0
          file: ./2.24.0-pg17-1.22.0/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_2-24-0-pg18-1-22-0:
    name: 2.24.0-pg18-1.22.0
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dontomika/timescaledb-with-toolkit
          tags: 2.24.0-pg18-1.22.0
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./2.24.0-pg18-1.22.0
          file: ./2.24.0-pg18-1.22.0/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

